CREATE TABLE tb_company_migrate_log (
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) not null,
  gmt_created datetime DEFAULT NULL,
  gmt_modified datetime DEFAULT NULL,
  min_pk_id integer DEFAULT NULL,
  table_name varchar(32) DEFAULT NULL,
  last_pk_id integer DEFAULT NULL,
  limit_size integer,
  init_done varchar(32),
  migrate_done varchar(32)
);

CREATE TABLE tb_platform_company (
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) not null,
  gmt_created datetime DEFAULT NULL,
  gmt_modified datetime DEFAULT NULL,
  name varchar(200),
  description varchar(2000) DEFAULT NULL,
  pinyin varchar(2000) DEFAULT NULL,
  init varchar(50) DEFAULT NULL,
  is_deleted integer,
  employee_import integer,
  employee_prefix varchar(50),
  tb_exam_company_id integer DEFAULT NULL
);


CREATE TABLE tb_hospital_company (
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) not null,
  name varchar(200),
  gmt_created datetime DEFAULT NULL,
  gmt_modified datetime DEFAULT NULL,
  platform_company_id integer ,
  organization_id integer,
  organization_name varchar(100),
  discount numeric,
  show_report integer DEFAULT '1',
  employee_import integer DEFAULT '0',
  settlement_mode integer DEFAULT NULL,
  his_name varchar(255) DEFAULT NULL,
  advance_export_order integer DEFAULT '1',
  send_exam_sms integer DEFAULT '0',
  send_exam_sms_days integer DEFAULT '1',
  pinyin varchar(2000) DEFAULT NULL,
  employee_prefix varchar(100) DEFAULT NULL,
  is_deleted integer DEFAULT '0',
  tb_exam_company_id integer DEFAULT NULL,
  examination_address varchar(50) default null,
  examreport_interval_time integer default null
);

CREATE TABLE tb_channel_company (
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) not null,
  name varchar(200),
  gmt_created datetime DEFAULT NULL,
  gmt_modified datetime DEFAULT NULL,
  platform_company_id integer,
  organization_id integer,
  organization_name varchar(100),
  discount numeric DEFAULT '1.000000000',
  settlement_mode integer DEFAULT NULL,
  send_exam_sms integer DEFAULT '0',
  send_exam_sms_days integer DEFAULT '1',
  is_deleted integer DEFAULT '0',
  pinyin varchar(50) DEFAULT NULL,
  description varchar(2000) DEFAULT NULL,
  tb_exam_company_id integer DEFAULT NULL
);

CREATE TABLE tb_hospital_exam_company_relation (
  hospital_id integer DEFAULT NULL,
  company_id integer DEFAULT NULL,
  discount numeric DEFAULT '1.000000000',
  show_report integer DEFAULT '1' ,
  show_invoice integer DEFAULT '1',
  employee_import integer NOT NULL DEFAULT '0',
  create_time datetime DEFAULT NULL,
  update_time datetime DEFAULT NULL,
  settlement_mode integer DEFAULT NULL,
  support_anytime_import integer DEFAULT '1',
  company_alias varchar(100) DEFAULT NULL ,
  his_name varchar(255) DEFAULT NULL ,
  status integer DEFAULT '1',
  advance_export_order integer DEFAULT '1',
  send_exam_sms integer DEFAULT '0',
  send_exam_sms_days integer DEFAULT '1',
  examination_address varchar(50),
  examreport_interval_time integer
);

CREATE TABLE tb_exam_company (
  id integer NOT NULL ,
  name varchar(100),
  pinyin varchar(100) DEFAULT NULL ,
  type integer DEFAULT '1' ,
  prefix varchar(64) DEFAULT NULL ,
  description varchar(100) DEFAULT NULL,
  reference_count_by_hosp integer DEFAULT '0'
);

