CREATE TABLE tb_area (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  	area_name VARCHAR(50) NOT null,
  	PRIMARY KEY (id)
);
CREATE TABLE tb_province
(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	province_id INTEGER NOT null,
	province_name VARCHAR(20) NOT null,
	parent_id INTEGER NOT null ,
	PRIMARY KEY (id)
);
CREATE TABLE tb_employee (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  gmt_created datetime DEFAULT NULL,
  gmt_modified datetime DEFAULT NULL,
  login_name varchar(50) DEFAULT NULL,
  employee_no varchar(50) DEFAULT NULL,
  employee_name varchar(50) DEFAULT NULL,
  nick_name varchar(50) DEFAULT NULL,
  password varchar(100) DEFAULT NULL,
  status INTEGER DEFAULT NULL,
  mobile varchar(20) DEFAULT NULL,
  salt varchar(20) DEFAULT NULL,
  pinyin varchar(100)default null,
  PRIMARY KEY (id)
);

CREATE TABLE tb_department_employee (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  department_id INTEGER NOT NULL,
  employee_id INTEGER NOT NULL ,
  PRIMARY KEY (id)
);